[package]
name = "cryptors"
description = "All-in-one cryptographic Rust library supporting AES, DES, DSA, ECDH, ECDSA, Ed25519, Elliptic Curves, HKDF, HMAC, HPKE, MD5, ML-DSA, ML-KEM, PBKDF2, RC4, RSA, SHA-1, SHA-256, SHA-3, and SHA-512"
repository = "https://github.com/matteobovetti/cryptors"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
readme = "README.md"
keywords = ["crypto", "cryptography", "library"]
categories = ["cryptography"]

[dependencies]
# MUST: This crate is a pure Rust implementation, so no dependencies are needed.

[profile.release]
lto = true
codegen-units = 1
